version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  api:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - 3000:3000
    working_dir: /api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - ./api:/api
