version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: db.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
  api:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run start"
    working_dir: /usr/src/api
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./api:/usr/src/api
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./front:/user/src/front
