version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: db.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #     target: development
  #   command: sh -c "yarn run start"
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   links:
  #     - db
  #   volumes:
  #     - ./api:/usr/src/app
